### ISSUE TITLE
[FEATURE] - [IMAGE] 이미지 저장 기능 구현하기

### ISSUE THREAD

**Issue by fakerdeft** [hi-medi/hi-medi#3]
# 설명
- 이미지 S3에 업로드하는 기능 구현

# TODO
- [x] AWS S3 버킷 생성
- [x] AWS IAM 계정 생성
- [x] client-s3, multer, multer-s3 사용해서 S3에 이미지 한 장 업로드
- [x] 업로드된 이미지의 URL을 MongoDB에 저장
